"""add_gender_to_account

Revision ID: 5af2743b8dc5
Revises: 9e78122f974d
Create Date: 2026-06-07 00:10:13.842848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.encrypted_type

# revision identifiers, used by Alembic.
revision: str = '5af2743b8dc5'
down_revision: Union[str, None] = '9e78122f974d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_action_limits_date'), 'account_action_limits', ['date'], unique=False)
    op.add_column('accounts', sa.Column('gender', sa.String(), nullable=True))
    op.alter_column('accounts', 'api_hash',
               existing_type=sa.VARCHAR(),
               type_=app.db.encrypted_type.EncryptedString(),
               existing_nullable=False)
    op.alter_column('accounts', 'session_string',
               existing_type=sa.VARCHAR(),
               type_=app.db.encrypted_type.EncryptedString(),
               existing_nullable=True)
    op.drop_constraint(op.f('accounts_proxy_id_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'proxies', ['proxy_id'], ['id'], ondelete='SET NULL')
    op.alter_column('action_logs', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_action_logs_account_id'), 'action_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_action_logs_project_id'), 'action_logs', ['project_id'], unique=False)
    op.alter_column('ai_settings', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('dialogs', 'chatting', 'commenting', name='aitype', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'dialogs'::character varying"))
    op.create_foreign_key(None, 'ai_settings', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('campaign_recipients', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', 'FAILED_RETRY', 'SKIPPED', name='recipientstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_campaign_recipients_id'), 'campaign_recipients', ['id'], unique=False)
    op.drop_constraint(op.f('campaigns_template_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'message_templates', ['template_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('comment_drafts', 'status',
               existing_type=postgresql.ENUM('draft', 'running', 'paused', 'completed', 'failed', 'stopped', name='commenttaskstatus'),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.create_index(op.f('ix_comment_drafts_account_id'), 'comment_drafts', ['account_id'], unique=False)
    op.create_index(op.f('ix_comment_drafts_source_id'), 'comment_drafts', ['source_id'], unique=False)
    op.create_index(op.f('ix_comment_drafts_task_id'), 'comment_drafts', ['task_id'], unique=False)
    op.drop_constraint(op.f('comment_drafts_account_id_fkey'), 'comment_drafts', type_='foreignkey')
    op.drop_constraint(op.f('comment_drafts_source_id_fkey'), 'comment_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'comment_drafts', 'telegram_sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment_drafts', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_comment_logs_account_id'), 'comment_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_comment_logs_draft_id'), 'comment_logs', ['draft_id'], unique=False)
    op.create_index(op.f('ix_comment_logs_source_id'), 'comment_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_comment_logs_task_id'), 'comment_logs', ['task_id'], unique=False)
    op.drop_constraint(op.f('comment_logs_draft_id_fkey'), 'comment_logs', type_='foreignkey')
    op.drop_constraint(op.f('comment_logs_source_id_fkey'), 'comment_logs', type_='foreignkey')
    op.drop_constraint(op.f('comment_logs_account_id_fkey'), 'comment_logs', type_='foreignkey')
    op.create_foreign_key(None, 'comment_logs', 'telegram_sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comment_logs', 'comment_drafts', ['draft_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comment_logs', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.alter_column('comment_tasks', 'source_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('comment_tasks', 'account_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_foreign_key(None, 'group_tasks', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_message_logs_account_id'), 'message_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_message_logs_campaign_id'), 'message_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_logs_contact_id'), 'message_logs', ['contact_id'], unique=False)
    op.drop_constraint(op.f('message_logs_campaign_id_fkey'), 'message_logs', type_='foreignkey')
    op.drop_constraint(op.f('message_logs_account_id_fkey'), 'message_logs', type_='foreignkey')
    op.drop_constraint(op.f('message_logs_contact_id_fkey'), 'message_logs', type_='foreignkey')
    op.create_foreign_key(None, 'message_logs', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_logs', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_logs', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.alter_column('proxies', 'password',
               existing_type=sa.VARCHAR(),
               type_=app.db.encrypted_type.EncryptedString(),
               existing_nullable=True)
    op.create_foreign_key(None, 'reaction_tasks', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('safety_drafts', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('pending', 'approved', 'rejected', 'published', name='draftstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('safety_drafts', 'moderation_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('safety_drafts', 'risk_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('source_allowlist', 'source_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('chat', 'channel', 'group', name='sourcetype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_allowlist', 'source_type',
               existing_type=sa.Enum('chat', 'channel', 'group', name='sourcetype'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('safety_drafts', 'risk_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('safety_drafts', 'moderation_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('safety_drafts', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'published', name='draftstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_constraint(None, 'reaction_tasks', type_='foreignkey')
    op.alter_column('proxies', 'password',
               existing_type=app.db.encrypted_type.EncryptedString(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.create_foreign_key(op.f('message_logs_contact_id_fkey'), 'message_logs', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(op.f('message_logs_account_id_fkey'), 'message_logs', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('message_logs_campaign_id_fkey'), 'message_logs', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index(op.f('ix_message_logs_contact_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_campaign_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_account_id'), table_name='message_logs')
    op.drop_constraint(None, 'group_tasks', type_='foreignkey')
    op.alter_column('comment_tasks', 'account_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('comment_tasks', 'source_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'comment_logs', type_='foreignkey')
    op.drop_constraint(None, 'comment_logs', type_='foreignkey')
    op.drop_constraint(None, 'comment_logs', type_='foreignkey')
    op.create_foreign_key(op.f('comment_logs_account_id_fkey'), 'comment_logs', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('comment_logs_source_id_fkey'), 'comment_logs', 'telegram_sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('comment_logs_draft_id_fkey'), 'comment_logs', 'comment_drafts', ['draft_id'], ['id'])
    op.drop_index(op.f('ix_comment_logs_task_id'), table_name='comment_logs')
    op.drop_index(op.f('ix_comment_logs_source_id'), table_name='comment_logs')
    op.drop_index(op.f('ix_comment_logs_draft_id'), table_name='comment_logs')
    op.drop_index(op.f('ix_comment_logs_account_id'), table_name='comment_logs')
    op.drop_constraint(None, 'comment_drafts', type_='foreignkey')
    op.drop_constraint(None, 'comment_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('comment_drafts_source_id_fkey'), 'comment_drafts', 'telegram_sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('comment_drafts_account_id_fkey'), 'comment_drafts', 'accounts', ['account_id'], ['id'])
    op.drop_index(op.f('ix_comment_drafts_task_id'), table_name='comment_drafts')
    op.drop_index(op.f('ix_comment_drafts_source_id'), table_name='comment_drafts')
    op.drop_index(op.f('ix_comment_drafts_account_id'), table_name='comment_drafts')
    op.alter_column('comment_drafts', 'status',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('draft', 'running', 'paused', 'completed', 'failed', 'stopped', name='commenttaskstatus'),
               existing_nullable=True)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_template_id_fkey'), 'campaigns', 'message_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_campaign_recipients_id'), table_name='campaign_recipients')
    op.alter_column('campaign_recipients', 'status',
               existing_type=sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', 'FAILED_RETRY', 'SKIPPED', name='recipientstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'ai_settings', type_='foreignkey')
    op.alter_column('ai_settings', 'type',
               existing_type=sa.Enum('dialogs', 'chatting', 'commenting', name='aitype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'dialogs'::character varying"))
    op.drop_index(op.f('ix_action_logs_project_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_account_id'), table_name='action_logs')
    op.alter_column('action_logs', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_proxy_id_fkey'), 'accounts', 'proxies', ['proxy_id'], ['id'])
    op.alter_column('accounts', 'session_string',
               existing_type=app.db.encrypted_type.EncryptedString(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('accounts', 'api_hash',
               existing_type=app.db.encrypted_type.EncryptedString(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('accounts', 'gender')
    op.drop_index(op.f('ix_account_action_limits_date'), table_name='account_action_limits')
    # ### end Alembic commands ###
