$env:PYTHONIOENCODING="utf-8"

Write-Host "STAGE 1: VIBE CODING"
python -m hh_applicant_tool apply-vacancies --search "vibe coding OR vibecoding OR вайб-кодинг OR вайбкодинг OR вайб кодинг" --area 113 --schedule remote --excluded-filter "(?i)senior|middle|junior|python\s*разработчик|javascript|php|java|c\+\+|golang|react|angular|vue|devops|docker|kubernetes|backend|frontend|fullstack|1c|1с|опыт от 3 лет|опыт от 3-х лет|от 3 до 6 лет|продажам|клиентами|маркетплейс|wildberries|ozon|\bwb\b|маркетолог|таргетолог|\bsmm\b|\bseo\b|оператор|колл-центр|call-центр|аккаунт|account|закупкам|копирайтер|дизайнер|руководител|директор|\bhead\b|\bchief\b|\bhr\b|рекрутер|бухгалтер|юрист|экономист|pr-менеджер|\bpr\b|пиар|логист|диспетчер" --letter-file "letter.txt" -f --max-responses 200

Write-Host "STAGE 2: MAIN AUTOMATION"
python -m hh_applicant_tool apply-vacancies --search "автоматизация бизнеса OR чат-боты OR нейросети OR airtable OR aircode OR make OR zapier" --area 113 --schedule remote --excluded-filter "(?i)senior|middle|junior|python\s*разработчик|javascript|php|java|c\+\+|golang|react|angular|vue|devops|docker|kubernetes|backend|frontend|fullstack|1c|1с|опыт от 3 лет|опыт от 3-х лет|от 3 до 6 лет|продажам|клиентами|маркетплейс|wildberries|ozon|\bwb\b|маркетолог|таргетолог|\bsmm\b|\bseo\b|оператор|колл-центр|call-центр|аккаунт|account|закупкам|копирайтер|дизайнер|руководител|директор|\bhead\b|\bchief\b|\bhr\b|рекрутер|бухгалтер|юрист|экономист|pr-менеджер|\bpr\b|пиар|логист|диспетчер" --letter-file "letter.txt" -f --max-responses 200

Write-Host "STAGE 3: BROAD SEARCH"
python -m hh_applicant_tool apply-vacancies --search "интегратор OR no-code OR low-code OR оптимизация процессов OR внедрение OR ИИ OR GPT OR нейросети" --area 113 --schedule remote --excluded-filter "(?i)senior|middle|junior|python\s*разработчик|javascript|php|java|c\+\+|golang|react|angular|vue|devops|docker|kubernetes|backend|frontend|fullstack|1c|1с|опыт от 3 лет|опыт от 3-х лет|от 3 до 6 лет|продажам|клиентами|маркетплейс|wildberries|ozon|\bwb\b|маркетолог|таргетолог|\bsmm\b|\bseo\b|оператор|колл-центр|call-центр|аккаунт|account|закупкам|копирайтер|дизайнер|руководител|директор|\bhead\b|\bchief\b|\bhr\b|рекрутер|бухгалтер|юрист|экономист|pr-менеджер|\bpr\b|пиар|логист|диспетчер" --letter-file "letter.txt" -f --max-responses 200
