// Calendar styles configuration
export const STYLES = {
  minimal: {
    name: 'Минималистичный',
    description: 'Много воздуха, чистые линии, приглушённые цвета',
    colors: {
      bg: 'bg-zinc-50',
      card: 'bg-white',
      primary: 'text-zinc-900',
      secondary: 'text-zinc-500',
      accent: 'text-zinc-600',
      border: 'border-zinc-200',
      hover: 'hover:bg-zinc-100',
      today: 'bg-zinc-900 text-white',
      selected: 'ring-1 ring-zinc-900',
      bookingDot: 'bg-zinc-900',
    },
    font: 'font-light',
    radius: 'rounded-none',
    shadow: 'shadow-none',
  },
  dark: {
    name: 'Тёмная тема',
    description: 'Современный dark mode с акцентами',
    colors: {
      bg: 'bg-zinc-950',
      card: 'bg-zinc-900',
      primary: 'text-zinc-100',
      secondary: 'text-zinc-400',
      accent: 'text-zinc-300',
      border: 'border-zinc-800',
      hover: 'hover:bg-zinc-800',
      today: 'bg-sky-500 text-white',
      selected: 'ring-2 ring-sky-500',
      bookingDot: 'bg-sky-500',
    },
    font: 'font-normal',
    radius: 'rounded-xl',
    shadow: 'shadow-xl shadow-black/20',
  },
  vibrant: {
    name: 'Яркий и контрастный',
    description: 'Насыщенные цвета, чёткие границы',
    colors: {
      bg: 'bg-gradient-to-br from-indigo-50 to-purple-50',
      card: 'bg-white border-2 border-zinc-900',
      primary: 'text-zinc-900',
      secondary: 'text-zinc-600',
      accent: 'text-indigo-600',
      border: 'border-zinc-900',
      hover: 'hover:bg-indigo-50',
      today: 'bg-indigo-600 text-white',
      selected: 'ring-2 ring-indigo-600',
      bookingDot: 'bg-indigo-600',
    },
    font: 'font-semibold',
    radius: 'rounded-2xl',
    shadow: 'shadow-xl shadow-indigo-900/10',
  },
  friendly: {
    name: 'Мягкий и дружелюбный',
    description: 'Скруглённые углы, пастельные тона',
    colors: {
      bg: 'bg-gradient-to-br from-amber-50 to-orange-50',
      card: 'bg-white rounded-3xl',
      primary: 'text-amber-900',
      secondary: 'text-amber-600',
      accent: 'text-orange-500',
      border: 'border-amber-100',
      hover: 'hover:bg-amber-50',
      today: 'bg-amber-400 text-amber-900',
      selected: 'ring-2 ring-amber-400',
      bookingDot: 'bg-amber-400',
    },
    font: 'font-medium',
    radius: 'rounded-3xl',
    shadow: 'shadow-lg shadow-amber-200/50',
  },
}

export const STATUS_STYLES = {
  minimal: {
    upcoming: 'bg-zinc-100 text-zinc-700 border-zinc-200',
    completed: 'bg-zinc-50 text-zinc-400 border-zinc-100',
    cancelled: 'bg-red-50 text-red-600 border-red-100',
    no_show: 'bg-orange-50 text-orange-600 border-orange-100',
  },
  dark: {
    upcoming: 'bg-sky-900/30 text-sky-400 border-sky-800',
    completed: 'bg-zinc-800 text-zinc-500 border-zinc-700',
    cancelled: 'bg-red-900/30 text-red-400 border-red-900',
    no_show: 'bg-orange-900/30 text-orange-400 border-orange-900',
  },
  vibrant: {
    upcoming: 'bg-indigo-100 text-indigo-700 border-indigo-200',
    completed: 'bg-zinc-100 text-zinc-500 border-zinc-200',
    cancelled: 'bg-red-100 text-red-700 border-red-200',
    no_show: 'bg-orange-100 text-orange-700 border-orange-200',
  },
  friendly: {
    upcoming: 'bg-amber-100 text-amber-700 border-amber-200',
    completed: 'bg-orange-50 text-orange-500 border-orange-100',
    cancelled: 'bg-red-50 text-red-600 border-red-100',
    no_show: 'bg-orange-100 text-orange-700 border-orange-200',
  },
}